server:
  port: 8881

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gtl_oa?characterEncoding=utf-8&useSSL=true
    password: root
    username: root